/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package isf.install.loader;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author raok1
 */
public class LaunchPanel extends javax.swing.JPanel {

    // private String img;
    private javax.swing.JLabel current;
    private javax.swing.JLabel latest;
    private javax.swing.JProgressBar pb;
    private javax.swing.JLabel status;
    private javax.swing.JLabel lblBg;

    /**
     * Creates new form LaunchPanel
     */
    public LaunchPanel(String image) {
        setLayout(new java.awt.BorderLayout());

        lblBg = new javax.swing.JLabel(new ImageIcon(getClass().getClassLoader().getResource("images/" + image)));
        lblBg.setLayout(new BorderLayout());
        // setPreferredSize(new java.awt.Dimension(400, 200));
        // setVerifyInputWhenFocusTarget(false);




        JPanel core = new JPanel() {
            /*  @Override
             protected void paintComponent(Graphics g) {
             super.paintComponent(g);
             Graphics2D g2d = (Graphics2D) g;
             g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
             int w = getWidth();
             int h = getHeight();
             Color color1 = new Color(245, 235, 230);
             Color color2 = new Color(235, 201, 168);
             GradientPaint gp = new GradientPaint(0, 60, color1, w, 100, color2);
             g2d.setPaint(gp);
             g2d.fillRect(0, 60, w, 100);
             }*/
        };
        core.setOpaque(false);
        core.setPreferredSize(new Dimension(461, 140));
        core.setBorder(BorderFactory.createEmptyBorder(120, 50, 10, 20));
        java.awt.GridBagConstraints gridBagConstraints;

        current = new javax.swing.JLabel();
        current.setForeground(new Color(255, 255, 80));
        current.setFont(new Font("Tahoma", Font.BOLD, 14));
        pb = new javax.swing.JProgressBar();
        latest = new javax.swing.JLabel();
        latest.setForeground(new Color(255, 255, 80));
        latest.setFont(new Font("Tahoma", Font.BOLD, 14));
        status = new javax.swing.JLabel();
        status.setForeground(new Color(255, 255, 80));
        status.setFont(new Font("Tahoma", Font.BOLD, 14));
        core.setLayout(new java.awt.GridBagLayout());

        current.setText("Current Version:");
        current.setMaximumSize(new java.awt.Dimension(300, 20));
        current.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        core.add(current, gridBagConstraints);

        latest.setText("Latest Version:");
        latest.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        core.add(latest, gridBagConstraints);

        status.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        status.setText("Checking for any updates on server:");
        status.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        core.add(status, gridBagConstraints);

        pb.setIndeterminate(true);
        pb.setPreferredSize(new java.awt.Dimension(300, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        core.add(pb, gridBagConstraints);


        latest.setVisible(false);
        pb.setVisible(false);
        //core.setLayout
        lblBg.add(core, BorderLayout.CENTER);
        add(lblBg, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(461, 140));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>                        
    // Variables declaration - do not modify                     
    // End of variables declaration                   

    public void setVersions(String c, String s) {
        current.setText("Current Version:" + c);
        latest.setText("Server Version:" + s);
        if (!c.equalsIgnoreCase(s)) {
            pb.setEnabled(true);
            pb.setVisible(true);
            latest.setVisible(true);
        }

    }

    public void setProgress(String s) {
        pb.setIndeterminate(true);
        status.setText(" Downloading file " + s);
    }

    public void setProgress(String s, boolean flag) {
        pb.setIndeterminate(true);
        status.setText(" " + s);
    }

    public void stopLoad() {
        pb.setIndeterminate(false);
        pb.setEnabled(false);
        pb.setVisible(false);
        pb.setIndeterminate(false);
        latest.setVisible(false);
        status.setText("");

    }
}
